name: Minify Workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
          fetch-depth: 0

      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:2.0.0
        with:
          add_suffix: false     # Optional

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: 'gh_pages'
