name: Minify Workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:2.0.0

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: 'to-be-made-master'
      - name: Commit Minified Code
